### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Pianz980** [ERLANRAHMAT/BETABOTZ-MD3#1]
Ada yg error' di bagian Module bg

**Comment by JER-OFC** [comment]
> Ada yg error' di bagian Module bg

Bisa kirim ss an di bagian erornya ?

**Comment by Pianz980** [comment]
> > Ada yg error' di bagian Module bg
> 
> Bisa kirim ss an di bagian erornya ?

![Screenshot_2024-06-28-06-21-02-21](https://github.com/ERLANRAHMAT/BETABOTZ-MD3/assets/173269095/e2d32c26-7caa-4566-b033-bab5cf7803d6)

**Comment by JER-OFC** [comment]
> > > Ada yg error' di bagian Module bg
> > 
> > 
> > Bisa kirim ss an di bagian erornya ?
> 
> ![Screenshot_2024-06-28-06-21-02-21](https://private-user-images.githubusercontent.com/173269095/344135361-e2d32c26-7caa-4566-b033-bab5cf7803d6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2NjM3NjAsIm5iZiI6MTcxOTY2MzQ2MCwicGF0aCI6Ii8xNzMyNjkwOTUvMzQ0MTM1MzYxLWUyZDMyYzI2LTdjYWEtNDU2Ni1iMDMzLWJhYjVjZjc4MDNkNi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyOVQxMjE3NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NDFlNzQ1NjE4MzVjYjQ0MWVmZTMzMTFjMzliODQ2ZWRmMTAyYmU3ZGQ4MzAyNDVjZjI2MTQ0MzQ3ZGM1ZjY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mKU6Aos9o7UzGF1oxtDg4FkseNRt05AJv1RW7QXepgc)

Coba download ulang dan install ulang ya, soalnya di saya ga eror, runtime pun ben hari”
